"""Remove foo and bar columns

Revision ID: 9c262ff3ac88
Revises: cf0bc5418629
Create Date: 2025-04-24 09:55:37.012451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c262ff3ac88"
down_revision: Union[str, None] = "cf0bc5418629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_foo_bar", "user", type_="unique")
    op.drop_column("user", "foo")
    op.drop_column("user", "bar")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("bar", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("foo", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("uq_user_foo_bar", "user", ["foo", "bar"])
    # ### end Alembic commands ###
