"""add user table

Revision ID: cf0bc5418629
Revises: e1897afac4c8
Create Date: 2025-04-24 09:35:37.186358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf0bc5418629"
down_revision: Union[str, None] = "e1897afac4c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user",
        sa.Column("hashed_password", sa.String(length=200), nullable=False, server_default='default_password'),
    )

    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
