"""add likes table

Revision ID: f702e90d101d
Revises: 537491c5c7d2
Create Date: 2025-05-05 15:59:02.226809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f702e90d101d"
down_revision: Union[str, None] = "537491c5c7d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "likes", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "likes", "post_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("likes_user_id_post_id_key", "likes", type_="unique")
    op.create_unique_constraint("unique_like", "likes", ["user_id", "post_id"])
    op.create_foreign_key(
        op.f("fk_likes_user_id_users"), "likes", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_likes_post_id_posts"), "likes", "posts", ["post_id"], ["id"]
    )
    op.drop_column("likes", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "likes",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("fk_likes_post_id_posts"), "likes", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_likes_user_id_users"), "likes", type_="foreignkey"
    )
    op.drop_constraint("unique_like", "likes", type_="unique")
    op.create_unique_constraint(
        "likes_user_id_post_id_key", "likes", ["user_id", "post_id"]
    )
    op.alter_column(
        "likes", "post_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "likes", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
