"""Add is_blocked and blocked_until to posts

Revision ID: 28049d475091
Revises: f696d1e44ec5
Create Date: 2025-04-30 12:54:15.111778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28049d475091"
down_revision: Union[str, None] = "f696d1e44ec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("is_blocked", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("blocked_until", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "blocked_until")
    op.drop_column("posts", "is_blocked")
    # ### end Alembic commands ###
