"""upgrade table

Revision ID: afb94d0215c7
Revises: cc052fd6207d
Create Date: 2025-04-17 14:59:36.280969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afb94d0215c7"
down_revision: Union[str, None] = "cc052fd6207d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("foo", sa.Integer(), nullable=False))
    op.add_column("user", sa.Column("bar", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        op.f("uq_user_foo_bar"), "user", ["foo", "bar"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_foo_bar"), "user", type_="unique")
    op.drop_column("user", "bar")
    op.drop_column("user", "foo")
    # ### end Alembic commands ###
